-- 코드를 입력하세요
SELECT distinct FIRST_HALF.FLAVOR from FIRST_HALF join ICECREAM_INFO 
on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE TOTAL_ORDER > 3000 and INGREDIENT_TYPE = 'fruit_based'
order by TOTAL_ORDER DESC;